# Generated by Django 3.0.6 on 2020-08-20 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmproduto', models.CharField(max_length=50)),
                ('precoprod', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoCargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmtipocargo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmtipoproduto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor', models.CharField(max_length=50)),
                ('quantidade', models.FloatField()),
                ('dtcriacao', models.DateTimeField(editable=False)),
                ('dtmodificacao', models.DateTimeField(editable=False)),
                ('fkproduto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projpad.Produto')),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='fktipoprod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projpad.TipoProduto'),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('remuneracao', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fkcargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projpad.TipoCargo')),
            ],
        ),
    ]
