# Generated by Django 3.0.6 on 2020-08-24 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projpad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda_Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fkproduto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projpad.Produto')),
                ('fkvenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projpad.Venda')),
            ],
        ),
    ]
