# Generated by Django 3.0.6 on 2020-08-24 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projpad', '0002_venda_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='fkproduto',
        ),
    ]
