# Generated by Django 3.0.6 on 2020-08-27 18:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projpad', '0003_remove_venda_fkproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='resumo',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
