# Generated by Django 3.0.6 on 2020-09-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projpad', '0005_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='fkcargo',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='remuneracao',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='resumo',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='sobrenome',
            field=models.CharField(max_length=255),
        ),
    ]
