# Generated by Django 3.0.6 on 2020-09-02 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projpad', '0006_auto_20200901_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
