# Generated by Django 3.0.6 on 2020-09-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projpad', '0007_auto_20200902_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproduto',
            name='nmtipoproduto',
            field=models.CharField(max_length=255),
        ),
    ]
