# Generated by Django 3.0.6 on 2020-09-03 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projpad', '0009_auto_20200903_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='fktipoprod',
        ),
    ]
