# Generated by Django 3.0.6 on 2020-09-14 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projpad', '0010_remove_produto_fktipoprod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='fkcargo',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, to='projpad.TipoCargo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='remuneracao',
            field=models.DecimalField(decimal_places=2, default=32, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='fktipoprod',
            field=models.ForeignKey(default=321, on_delete=django.db.models.deletion.CASCADE, to='projpad.TipoProduto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipoproduto',
            name='nmtipoproduto',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='venda',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projpad.Funcionario'),
        ),
    ]
