# Generated by Django 3.0.6 on 2020-09-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projpad', '0011_auto_20200914_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='venda_produto',
            name='quantidade',
            field=models.FloatField(default=1),
        ),
    ]
